-- Enable necessary extensions
create extension if not exists "pg_trgm";
create extension if not exists "pg_cron";
create extension if not exists "pg_net";

-- Create stories table
create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  display_title text not null,
  norm_title text not null,
  trgm_key text not null,
  provinces text[] default '{}',
  deaths int,
  injuries int,
  source_count int default 1,
  first_published timestamptz not null,
  last_published timestamptz not null,
  created_at timestamptz default now()
);

-- Create articles table
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  story_id bigint references public.stories(id) on delete cascade not null,
  source text not null,
  title text not null,
  url text unique not null,
  summary text,
  confidence text not null,
  published timestamptz not null,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists articles_story_id_idx on public.articles(story_id);
create index if not exists stories_first_published_idx on public.stories(first_published desc);
create index if not exists stories_trgm_key_idx on public.stories using gin (trgm_key gin_trgm_ops);

-- Helper function for finding matching stories via trigram (called by backend)
create or replace function find_candidate_stories(search_key text, window_start timestamptz, window_end timestamptz)
returns setof public.stories
language sql
as $$
  select * from public.stories
  where first_published between window_start and window_end
    and trgm_key % search_key -- uses pg_trgm similarity
  order by similarity(trgm_key, search_key) desc;
$$;
